package frontend;


import backend.LibrarianRole;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eyada
 */
public class BorrowBook extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame11
     */
    public BorrowBook() {
        super("Borrow Book");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        studentID = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        borrowdate = new javax.swing.JLabel();
        borrow = new javax.swing.JLabel();
        studentIDText = new javax.swing.JTextField();
        bookIDText = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));

        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(140, 56, 56));
        title.setText("Librarian Role");
        title.setPreferredSize(new java.awt.Dimension(100, 44));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 220, -1));

        subtitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        subtitle.setForeground(new java.awt.Color(140, 56, 56));
        subtitle.setText("Borrow Book");
        getContentPane().add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        studentID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentID.setForeground(new java.awt.Color(140, 56, 56));
        studentID.setText("Student ID");
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        bookID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookID.setForeground(new java.awt.Color(140, 56, 56));
        bookID.setText("Book ID");
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        borrowdate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        borrowdate.setForeground(new java.awt.Color(140, 56, 56));
        borrowdate.setText("Borrow Date");
        getContentPane().add(borrowdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        borrow.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        borrow.setForeground(new java.awt.Color(140, 56, 56));
        borrow.setText("Borrow");
        borrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowMouseExited(evt);
            }
        });
        getContentPane().add(borrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, -1, -1));

        studentIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentIDText.setForeground(new java.awt.Color(140, 56, 56));
        getContentPane().add(studentIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, -1));

        bookIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookIDText.setForeground(new java.awt.Color(140, 56, 56));
        getContentPane().add(bookIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, 180, -1));

        background.setBackground(new java.awt.Color(242, 239, 234));
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        new LibrarianMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void borrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowMouseClicked
        Date date = datechooser.getDate();
        if(date==null){
            JOptionPane.showMessageDialog(this,"Some fields are empty","EMPTY FIELDS",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            int x=GlobalVariables.l1.borrowBook(studentIDText.getText(), bookIDText.getText(),localDate);
        
            if(localDate.toString().isEmpty() ||studentIDText.getText().isEmpty() ||bookIDText.getText().isEmpty()){
                JOptionPane.showMessageDialog(this,"Some fields are empty","EMPTY FIELDS",JOptionPane.INFORMATION_MESSAGE);
            } 
            else if(x==0){
                JOptionPane.showMessageDialog(this,"All copies of the book with ID = "+bookIDText.getText()+" have been borrowed and no copy is left for the student with ID "+studentIDText.getText(),"NO COPIES LEFT",JOptionPane.INFORMATION_MESSAGE);    
            }
            else if(x==1){
                JOptionPane.showMessageDialog(this,"The student with ID="+studentIDText.getText()+" has already borrowed a copy of the book with ID= "+bookIDText.getText()+"and hasn't returned it yet.","ALREADY BORROWED ",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"The student with ID="+studentIDText.getText()+" has successfully borrowed a copy of the book with ID= "+bookIDText.getText()+".","SUCCESSFULLY BORROWED ",JOptionPane.INFORMATION_MESSAGE);
                clear(bookIDText);
                clear(studentIDText);
                datechooser.setCalendar(null);
            }
        }
    }//GEN-LAST:event_borrowMouseClicked

    private void borrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowMouseEntered
        borrow.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_borrowMouseEntered

    private void borrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowMouseExited
        borrow.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_borrowMouseExited

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      new LibrarianMain().setVisible(true);
        this.dispose();  // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    public void clear(JTextField t){
    t.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrowBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrowBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bookID;
    private javax.swing.JTextField bookIDText;
    private javax.swing.JLabel borrow;
    private javax.swing.JLabel borrowdate;
    private javax.swing.JLabel close;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel studentID;
    private javax.swing.JTextField studentIDText;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
