package frontend;


import backend.LibrarianRole;
import java.awt.Color;
import javax.swing.JFrame;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eyada
 */
public class LibrarianMain extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame3
     */

    public LibrarianMain(){
        super("Librarian Main");
        initComponents();
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        addbook = new javax.swing.JLabel();
        viewbooks = new javax.swing.JLabel();
        borrowbook = new javax.swing.JLabel();
        viewborrowedbooks = new javax.swing.JLabel();
        returnbook = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\icons8-close-64.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\icons8-minimize-64.png")); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(140, 56, 56));
        title.setText("Librarian Role");
        title.setPreferredSize(new java.awt.Dimension(100, 44));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        addbook.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        addbook.setForeground(new java.awt.Color(140, 56, 56));
        addbook.setText("Add book");
        addbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addbookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addbookMouseExited(evt);
            }
        });
        getContentPane().add(addbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        viewbooks.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        viewbooks.setForeground(new java.awt.Color(140, 56, 56));
        viewbooks.setText("View books");
        viewbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewbooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewbooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewbooksMouseExited(evt);
            }
        });
        getContentPane().add(viewbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        borrowbook.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        borrowbook.setForeground(new java.awt.Color(140, 56, 56));
        borrowbook.setText("Borrow book");
        borrowbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                borrowbookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                borrowbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                borrowbookMouseExited(evt);
            }
        });
        getContentPane().add(borrowbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        viewborrowedbooks.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        viewborrowedbooks.setForeground(new java.awt.Color(140, 56, 56));
        viewborrowedbooks.setText("View borrowed books");
        viewborrowedbooks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                viewborrowedbooksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                viewborrowedbooksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                viewborrowedbooksMouseExited(evt);
            }
        });
        getContentPane().add(viewborrowedbooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        returnbook.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        returnbook.setForeground(new java.awt.Color(140, 56, 56));
        returnbook.setText("Return book");
        returnbook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnbookMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnbookMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnbookMouseExited(evt);
            }
        });
        getContentPane().add(returnbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, -1, -1));

        logout.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        logout.setForeground(new java.awt.Color(140, 56, 56));
        logout.setText("Logout");
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutMouseExited(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 600, -1, -1));

        background.setBackground(new java.awt.Color(242, 239, 234));
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\35938460.jpg")); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 680));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        new LibrarianLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void addbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseEntered
        addbook.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_addbookMouseEntered

    private void addbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseExited
        addbook.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_addbookMouseExited

    private void viewbooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbooksMouseEntered
        viewbooks.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_viewbooksMouseEntered

    private void viewbooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbooksMouseExited
        viewbooks.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_viewbooksMouseExited

    private void borrowbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbookMouseEntered
        borrowbook.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_borrowbookMouseEntered

    private void borrowbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbookMouseExited
        borrowbook.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_borrowbookMouseExited

    private void viewborrowedbooksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewborrowedbooksMouseEntered
        viewborrowedbooks.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_viewborrowedbooksMouseEntered

    private void viewborrowedbooksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewborrowedbooksMouseExited
        viewborrowedbooks.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_viewborrowedbooksMouseExited

    private void returnbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseClicked
        new ReturnBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_returnbookMouseClicked

    private void returnbookMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseEntered
        returnbook.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_returnbookMouseEntered

    private void returnbookMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbookMouseExited
        returnbook.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_returnbookMouseExited

    private void logoutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseEntered
        logout.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_logoutMouseEntered

    private void logoutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseExited
        logout.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_logoutMouseExited

    private void addbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addbookMouseClicked
        new AddBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_addbookMouseClicked

    private void viewbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewbooksMouseClicked
        new ViewBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewbooksMouseClicked

    private void borrowbookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_borrowbookMouseClicked
        new BorrowBook().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_borrowbookMouseClicked

    private void viewborrowedbooksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_viewborrowedbooksMouseClicked
        new ViewBorrowedBooks().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_viewborrowedbooksMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        GlobalVariables.l1.logout();
        new LibrarySystem().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
new LibrarianLogin().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibrarianMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibrarianMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibrarianMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibrarianMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibrarianMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addbook;
    private javax.swing.JLabel background;
    private javax.swing.JLabel borrowbook;
    private javax.swing.JLabel close;
    private javax.swing.JLabel logout;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel returnbook;
    private javax.swing.JLabel title;
    private javax.swing.JLabel viewbooks;
    private javax.swing.JLabel viewborrowedbooks;
    // End of variables declaration//GEN-END:variables
}
