package frontend;


import backend.LibrarianRole;
import java.awt.Color;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author eyada
 */
public class ReturnBook extends javax.swing.JFrame {
    /**
     * Creates new form NewJFrame12
     */
    public ReturnBook() {
        super("Return Book");
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        close = new javax.swing.JLabel();
        minimize = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        subtitle = new javax.swing.JLabel();
        studentID = new javax.swing.JLabel();
        bookID = new javax.swing.JLabel();
        returndate = new javax.swing.JLabel();
        returnbutton = new javax.swing.JLabel();
        studentIDText = new javax.swing.JTextField();
        bookIDText = new javax.swing.JTextField();
        datechooser = new com.toedter.calendar.JDateChooser();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        close.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\icons8-close-64.png")); // NOI18N
        close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeMouseClicked(evt);
            }
        });
        getContentPane().add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, -1));

        minimize.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\icons8-minimize-64.png")); // NOI18N
        minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizeMouseClicked(evt);
            }
        });
        getContentPane().add(minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));

        title.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        title.setForeground(new java.awt.Color(140, 56, 56));
        title.setText("Librarian Role");
        title.setPreferredSize(new java.awt.Dimension(100, 44));
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 220, -1));

        subtitle.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        subtitle.setForeground(new java.awt.Color(140, 56, 56));
        subtitle.setText("Return Book");
        getContentPane().add(subtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        studentID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentID.setForeground(new java.awt.Color(140, 56, 56));
        studentID.setText("Student ID");
        getContentPane().add(studentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        bookID.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookID.setForeground(new java.awt.Color(140, 56, 56));
        bookID.setText("Book ID");
        getContentPane().add(bookID, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        returndate.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        returndate.setForeground(new java.awt.Color(140, 56, 56));
        returndate.setText("Return Date");
        getContentPane().add(returndate, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        returnbutton.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        returnbutton.setForeground(new java.awt.Color(140, 56, 56));
        returnbutton.setText("Return");
        returnbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                returnbuttonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                returnbuttonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                returnbuttonMouseExited(evt);
            }
        });
        getContentPane().add(returnbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 290, -1, -1));

        studentIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        studentIDText.setForeground(new java.awt.Color(140, 56, 56));
        studentIDText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDTextActionPerformed(evt);
            }
        });
        getContentPane().add(studentIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 180, -1));

        bookIDText.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        bookIDText.setForeground(new java.awt.Color(140, 56, 56));
        getContentPane().add(bookIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, -1));
        getContentPane().add(datechooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 180, -1));

        background.setBackground(new java.awt.Color(242, 239, 234));
        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\eyada\\Downloads\\35938460.jpg")); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeMouseClicked
        new LibrarianMain().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_closeMouseClicked

    private void minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_minimizeMouseClicked

    private void returnbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbuttonMouseClicked
        Date date = datechooser.getDate();
        if(date==null){
            JOptionPane.showMessageDialog(this,"Some fields are empty","EMPTY FIELDS",JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            LocalDate localDate = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
            double fee =GlobalVariables.l1.returnBook(studentIDText.getText(),bookIDText.getText(),localDate);
            if(studentIDText.getText().equals("") || bookIDText.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Some fields are empty","EMPTY FIELDS",JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"The student with ID="+studentIDText.getText()+" should pay a return fee of "+fee+" US dollars for the boook with ID "+bookIDText.getText()+".","RETURN FEES ",JOptionPane.INFORMATION_MESSAGE);
                clear(bookIDText);
                clear(studentIDText);
                datechooser.setCalendar(null);
            }
        }
    }//GEN-LAST:event_returnbuttonMouseClicked

    private void returnbuttonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbuttonMouseEntered
        returnbutton.setForeground(new Color(250,56,56));
    }//GEN-LAST:event_returnbuttonMouseEntered

    private void returnbuttonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_returnbuttonMouseExited
        returnbutton.setForeground(new Color(140,56,56));
    }//GEN-LAST:event_returnbuttonMouseExited

    private void studentIDTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDTextActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
new LibrarianMain().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosing
    public void clear(JTextField t){
    t.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReturnBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReturnBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bookID;
    private javax.swing.JTextField bookIDText;
    private javax.swing.JLabel close;
    private com.toedter.calendar.JDateChooser datechooser;
    private javax.swing.JLabel minimize;
    private javax.swing.JLabel returnbutton;
    private javax.swing.JLabel returndate;
    private javax.swing.JLabel studentID;
    private javax.swing.JTextField studentIDText;
    private javax.swing.JLabel subtitle;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
